version: "3"
services:
  db:
    build: mysql
    container_name: pls-db
    ports:
      - "3306:3306"
    networks:
      - plsnet
    volumes:
      - ./mysql/db:/var/lib/mysql
  web:
    build: nginx
    container_name: pls-web-server
    ports:
      - "8080:80"
    networks:
      - plsnet
    volumes:
      - ./nginx/src:/usr/share/nginx/html
    depends_on:
      - app
    environment:
      APP_SERVER: http://app:8080
  app:
    build: app
    container_name: pls-app
    networks:
      - plsnet
    depends_on:
      - db
networks:
  plsnet:
    driver: bridge
