version: "3"
services:
  db:
    build: mysql
    container_name: pls-db
    networks:
      - plsnet
    restart: always
  web:
    build: httpd
    container_name: pls-web-server
    ports:
      - "8080:80"
    networks:
      - plsnet
    volumes:
      - ./httpd/src:/usr/local/apache2/htdocs
    depends_on:
      - app
  app:
    build: tomcat
    container_name: pls-app-server
    networks:
      - plsnet
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    depends_on:
      - db
networks:
  plsnet:
    driver: bridge
