version: "3"
services:
  db:
    build: mysql
    container_name: pls-db
    restart: always
  web:
    build: httpd
    container_name: pls-web-server
    ports:
      - "8080:80"
    networks:
      - plsNet
    volumes:
      - ./httpd/src:/usr/local/apache2/htdocs
    depends_on:
      - db
  app:
    build: tomcat
    container_name: pls-app-server
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - plsNet
  networks:
    plsNet:
      driver: bridge
